name: Build wheels and sdist and upload everything to testPyPI

# This is triggered upon creating a release on GitHub.
on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  upload_pypi:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pysndbxbnjmnp
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/