name: Build wheels and sdist and upload everything to testPyPI

# This is triggerd upon creating a release on GitHub.
on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  upload_pypi:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PYSNDBXBNJMNP_ACCESS_TOKEN }}
          repository_url: https://test.pypi.org/legacy/